### ISSUE TITLE
Enable 'Open Links in VS' option doesn't do anything

### ISSUE THREAD

**Issue by smaillet** [luminous-software/developer-news#10]
### Installed product versions
- Visual Studio: VS 2019 16.5.4
- This extension: 1.3

### Description
If I set the _Enable 'Open Links in VS'_ option to False I expect links from the feed to open in my default browser and NOT in a VS Window.

### Steps to recreate
1. Open Settings for developer news
2. Set _Enable 'Open Links in VS'_ to false
3. Click OK to close the settings
4. Open Developer new feed window
5. Click on any link in the feed

### Current behavior
Opens a VS window, which is the opposite of what I changed the settings to do.

### Expected behavior
Open the page in my default browser.

**Comment by yannduran** [comment]
Thank you for bringing this to my attention Steven. There was a missing parameter value, which I've now fixed.

I've uploaded **v1.3.1** with the fix to the _Visual Studio Marketplace_.
