### ISSUE TITLE
Copy error on website

### ISSUE THREAD

**Issue by Ryan-Palmer** [luminous-software/developer-news#3]
Tiny thing - the instructions on the website say to enable the panel via Tools | Developer News but it is actually under View | Developer News :)

**Comment by yannduran** [comment]
Hi Ryan, thanks for your feedback! I just checkedand all my documentation says:

**Comment by yannduran** [comment]
I just found it! As you said, it was on the **_website_**.

Thanks again :-)

**Comment by RyanBuzzInteractive** [comment]
No worries, thanks for the plugin! :)

**Comment by yannduran** [comment]
You're welcome Ryan!

If you've got time, would you mind giving it a rating or a short review?

Thanks!

**Comment by RyanBuzzInteractive** [comment]
Sure no problem 👍

**Comment by yannduran** [comment]
Much appreciated!
