### ISSUE TITLE
Open links in default browser

### ISSUE THREAD

**Issue by bazile** [luminous-software/developer-news#4]
### Installed product versions
- Visual Studio: VS 2019 Enterprise v16.1.4
- This extension: 1.0.2

### Description
Please add option to open links in default browser instead of window inside Visual Studio. Leave current behavior by default.

### Current behavior
Links always open in browser inside Visual Studio.

### Expected behavior
After option "Open in default browser" is set to true links are opened in default browser.

**Comment by yannduran** [comment]
Great minds think alike!While I definitely prefer an internal browser, I understand that others feel the opposite way.

The option to open links in your default browser will indeed be coming soon. I just need to add the option to enable it to the settings.

Thanks for reaching out :-)

**Comment by yannduran** [comment]
Did you download the new version with this feature implemented?

If you did, and it's working how you expected, and you haven't left a rating/review yet, would you mind letting people know what you think of _Developer News_?

Thanks!

**Comment by bazile** [comment]
Yes, I did. It worked as expected.

Regarding review. VS marketplace allows only one review from one person. And I've already left one.

Thank you for a quick implementation.

**Comment by yannduran** [comment]
Thanks so much! And you're welcome. 

Don't hesitate to let me know if you ever have any more suggestions.
