### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ttoennies** [luminous-software/developer-news#9]
I received the following error when I tried to install the update.  I uninstalled and tried installing from scratch and received the same error. 
![2020-04-13_094035](https://user-images.githubusercontent.com/3342697/79129989-d5ca5080-7d6b-11ea-8b74-09bc12ea5e7c.png)

**Comment by yannduran** [comment]
Hi Tim, thanks for letting me know. I'll look into that straight away!

**Comment by yannduran** [comment]
I've uploaded an update that should fix this. Let me know if it's still a problem.

**Comment by InteXX** [comment]
The update fixed it for me. Thank you.

**Comment by ttoennies** [comment]
And for me as well. Thanks for the quick update.
